-- ============================================================
-- RaiseRing: Notes & Contact Tracking System
-- Run this in the Supabase SQL Editor
-- ============================================================

-- ============================================================
-- 1. CONTACT NOTES — Individual timestamped notes per contact
--    Replaces the single "notes" text field with a full history
-- ============================================================

create table contact_notes (
  id uuid primary key default uuid_generate_v4(),
  contact_id uuid not null references contacts(id) on delete cascade,
  organization_id uuid not null references organizations(id) on delete cascade,
  created_by uuid not null references users(id),

  -- The note content
  content text not null,

  -- What kind of note is this?
  note_type text not null default 'general' check (note_type in (
    'general',        -- free-form note
    'call_summary',   -- auto-generated from a call transcript
    'follow_up',      -- follow-up action or reminder
    'personal_detail', -- something personal the donor mentioned (kids, interests, etc.)
    'giving_history', -- info about past giving
    'relationship',   -- how the caller knows this person
    'research'        -- background research on the contact
  )),

  -- Optional link to the call that generated this note
  call_id uuid references calls(id) on delete set null,

  -- Was this auto-generated by AI or manually entered?
  source text not null default 'manual' check (source in ('manual', 'ai_transcript', 'ai_summary', 'import')),

  -- Pin important notes to the top of the contact's briefing card
  pinned boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ============================================================
-- 2. CONTACT TAGS — Flexible tagging system for contacts
--    e.g., "major donor", "finance committee", "board member",
--    "education supporter", "host potential"
-- ============================================================

create table tags (
  id uuid primary key default uuid_generate_v4(),
  organization_id uuid not null references organizations(id) on delete cascade,
  name text not null,
  color text not null default '#6366f1', -- hex color for display
  created_at timestamptz not null default now(),
  unique(organization_id, name)
);

create table contact_tags (
  id uuid primary key default uuid_generate_v4(),
  contact_id uuid not null references contacts(id) on delete cascade,
  tag_id uuid not null references tags(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(contact_id, tag_id)
);

-- ============================================================
-- 3. CONTACT INTERACTIONS — Timeline of all touchpoints
--    Every call, email, text, meeting, event attendance
--    This is the CRM backbone
-- ============================================================

create table contact_interactions (
  id uuid primary key default uuid_generate_v4(),
  contact_id uuid not null references contacts(id) on delete cascade,
  organization_id uuid not null references organizations(id) on delete cascade,
  created_by uuid not null references users(id),

  -- What type of interaction
  interaction_type text not null check (interaction_type in (
    'call',           -- phone call (linked to calls table)
    'text_sent',      -- follow-up text sent
    'email_sent',     -- follow-up email sent
    'letter_sent',    -- physical mail sent
    'meeting',        -- in-person meeting
    'event',          -- attended an event
    'voicemail',      -- left a voicemail
    'social_media',   -- social media interaction
    'introduction',   -- introduced to someone
    'other'
  )),

  -- Brief description
  description text,

  -- Outcome of the interaction
  outcome text check (outcome in (
    'positive',       -- good conversation, moving forward
    'neutral',        -- no strong signal either way
    'negative',       -- declined, not interested
    'no_contact',     -- didn't reach them
    null              -- not specified
  )),

  -- Link to related call record (if interaction_type = 'call')
  call_id uuid references calls(id) on delete set null,

  -- Dollar amount associated (pledge, donation, etc.)
  amount numeric,

  -- When did the interaction happen (may differ from created_at)
  interaction_date timestamptz not null default now(),

  created_at timestamptz not null default now()
);

-- ============================================================
-- 4. CONTACT STATUS TRACKING — Where is this contact in the
--    fundraising pipeline?
-- ============================================================

-- Add pipeline status columns to existing contacts table
alter table contacts add column if not exists
  pipeline_status text default 'new' check (pipeline_status in (
    'new',            -- just imported, never contacted
    'to_contact',     -- identified as someone to call
    'attempted',      -- tried to reach, no answer yet
    'in_conversation', -- have spoken, building relationship
    'asked',          -- made the ask
    'pledged',        -- pledged but not yet donated
    'donated',        -- donation received
    'declined',       -- explicitly declined
    'do_not_call',    -- asked not to be contacted
    'nurture'         -- not ready now, follow up later
  ));

-- When should we follow up with this contact?
alter table contacts add column if not exists
  next_follow_up timestamptz;

-- What should the follow-up be about?
alter table contacts add column if not exists
  follow_up_note text;

-- How many times have we attempted to reach them?
alter table contacts add column if not exists
  contact_attempts integer default 0;

-- When was the last interaction of any kind?
alter table contacts add column if not exists
  last_interaction_at timestamptz;

-- Total amount pledged by this contact (denormalized for fast queries)
alter table contacts add column if not exists
  total_pledged numeric default 0;

-- Total amount donated/fulfilled by this contact
alter table contacts add column if not exists
  total_donated numeric default 0;

-- Relationship strength score (1-5, updated by AI based on interactions)
alter table contacts add column if not exists
  relationship_score integer check (relationship_score between 1 and 5);

-- ============================================================
-- 5. FOLLOW-UP QUEUE — Scheduled follow-ups that surface
--    at the right time
-- ============================================================

create table follow_ups (
  id uuid primary key default uuid_generate_v4(),
  contact_id uuid not null references contacts(id) on delete cascade,
  organization_id uuid not null references organizations(id) on delete cascade,
  assigned_to uuid references users(id),

  -- What type of follow-up
  follow_up_type text not null check (follow_up_type in (
    'call_back',       -- donor asked to be called back
    'pledge_chase',    -- follow up on outstanding pledge
    'thank_you',       -- send a thank you
    're_solicit',      -- time to ask again
    'check_in',        -- relationship maintenance
    'event_invite',    -- invite to upcoming event
    'introduction',    -- make an introduction
    'send_info',       -- donor asked for more information
    'other'
  )),

  -- Description of what to do
  description text,

  -- When should this follow-up happen?
  due_date timestamptz not null,

  -- Priority (1 = highest)
  priority integer not null default 3 check (priority between 1 and 5),

  -- Status
  status text not null default 'pending' check (status in (
    'pending',      -- not yet done
    'completed',    -- done
    'skipped',      -- decided not to do
    'overdue'       -- past due date
  )),

  -- Completed details
  completed_at timestamptz,
  completed_by uuid references users(id),
  completion_notes text,

  -- Link to the call that generated this follow-up
  source_call_id uuid references calls(id) on delete set null,

  created_at timestamptz not null default now()
);

-- ============================================================
-- 6. DONATION RECORDS — Track actual money received
--    (separate from pledges — a pledge becomes a donation
--    when the money arrives)
-- ============================================================

create table donations (
  id uuid primary key default uuid_generate_v4(),
  contact_id uuid not null references contacts(id) on delete cascade,
  organization_id uuid not null references organizations(id) on delete cascade,
  pledge_id uuid references pledges(id) on delete set null,

  amount numeric not null,

  -- How did they donate?
  method text check (method in (
    'online',       -- ActBlue, website, etc.
    'check',        -- physical check
    'credit_card',  -- over the phone
    'cash',
    'wire',
    'other'
  )),

  -- Reference number (check number, ActBlue ID, etc.)
  reference text,

  -- Date the donation was received
  donated_at timestamptz not null default now(),

  -- Notes
  notes text,

  recorded_by uuid references users(id),
  created_at timestamptz not null default now()
);

-- ============================================================
-- 7. INDEXES for fast queries
-- ============================================================

create index idx_contact_notes_contact on contact_notes(contact_id);
create index idx_contact_notes_type on contact_notes(note_type);
create index idx_contact_notes_pinned on contact_notes(pinned) where pinned = true;
create index idx_contact_tags_contact on contact_tags(contact_id);
create index idx_contact_tags_tag on contact_tags(tag_id);
create index idx_tags_org on tags(organization_id);
create index idx_interactions_contact on contact_interactions(contact_id);
create index idx_interactions_org on contact_interactions(organization_id);
create index idx_interactions_date on contact_interactions(interaction_date);
create index idx_interactions_type on contact_interactions(interaction_type);
create index idx_contacts_pipeline on contacts(pipeline_status);
create index idx_contacts_follow_up on contacts(next_follow_up) where next_follow_up is not null;
create index idx_contacts_last_interaction on contacts(last_interaction_at);
create index idx_follow_ups_due on follow_ups(due_date) where status = 'pending';
create index idx_follow_ups_contact on follow_ups(contact_id);
create index idx_follow_ups_assigned on follow_ups(assigned_to) where status = 'pending';
create index idx_follow_ups_org on follow_ups(organization_id);
create index idx_donations_contact on donations(contact_id);
create index idx_donations_org on donations(organization_id);
create index idx_donations_date on donations(donated_at);

-- ============================================================
-- 8. ROW LEVEL SECURITY
-- ============================================================

alter table contact_notes enable row level security;
alter table tags enable row level security;
alter table contact_tags enable row level security;
alter table contact_interactions enable row level security;
alter table follow_ups enable row level security;
alter table donations enable row level security;

-- All new tables use the get_my_organization_id() function
-- from the previous RLS fix to avoid circular policies

create policy "Users see own org notes" on contact_notes
  for select to authenticated using (organization_id = public.get_my_organization_id());
create policy "Users can insert notes" on contact_notes
  for insert to authenticated with check (organization_id = public.get_my_organization_id());
create policy "Users can update own notes" on contact_notes
  for update to authenticated using (created_by = auth.uid());
create policy "Users can delete own notes" on contact_notes
  for delete to authenticated using (created_by = auth.uid());

create policy "Users see own org tags" on tags
  for select to authenticated using (organization_id = public.get_my_organization_id());
create policy "Users can create tags" on tags
  for insert to authenticated with check (organization_id = public.get_my_organization_id());
create policy "Users can delete tags" on tags
  for delete to authenticated using (organization_id = public.get_my_organization_id());

create policy "Users see own org contact tags" on contact_tags
  for select to authenticated using (
    contact_id in (select id from contacts where organization_id = public.get_my_organization_id())
  );
create policy "Users can tag contacts" on contact_tags
  for insert to authenticated with check (
    contact_id in (select id from contacts where organization_id = public.get_my_organization_id())
  );
create policy "Users can untag contacts" on contact_tags
  for delete to authenticated using (
    contact_id in (select id from contacts where organization_id = public.get_my_organization_id())
  );

create policy "Users see own org interactions" on contact_interactions
  for select to authenticated using (organization_id = public.get_my_organization_id());
create policy "Users can log interactions" on contact_interactions
  for insert to authenticated with check (organization_id = public.get_my_organization_id());
create policy "Users can update own interactions" on contact_interactions
  for update to authenticated using (created_by = auth.uid());

create policy "Users see own org follow ups" on follow_ups
  for select to authenticated using (organization_id = public.get_my_organization_id());
create policy "Users can create follow ups" on follow_ups
  for insert to authenticated with check (organization_id = public.get_my_organization_id());
create policy "Users can update own org follow ups" on follow_ups
  for update to authenticated using (organization_id = public.get_my_organization_id());
create policy "Users can delete own org follow ups" on follow_ups
  for delete to authenticated using (organization_id = public.get_my_organization_id());

create policy "Users see own org donations" on donations
  for select to authenticated using (organization_id = public.get_my_organization_id());
create policy "Users can record donations" on donations
  for insert to authenticated with check (organization_id = public.get_my_organization_id());
create policy "Users can update own org donations" on donations
  for update to authenticated using (organization_id = public.get_my_organization_id());

-- ============================================================
-- 9. AUTO-UPDATE TRIGGERS
-- ============================================================

-- Update contact_notes.updated_at on edit
create trigger contact_notes_updated_at
  before update on contact_notes
  for each row execute function update_updated_at();

-- Auto-update contacts.last_interaction_at when a new interaction is logged
create or replace function update_contact_last_interaction()
returns trigger as $$
begin
  update contacts
  set last_interaction_at = new.interaction_date,
      contact_attempts = contact_attempts + case when new.interaction_type = 'call' then 1 else 0 end
  where id = new.contact_id;
  return new;
end;
$$ language plpgsql security definer;

create trigger interaction_updates_contact
  after insert on contact_interactions
  for each row execute function update_contact_last_interaction();

-- Auto-update contacts.total_donated when a donation is recorded
create or replace function update_contact_total_donated()
returns trigger as $$
begin
  update contacts
  set total_donated = coalesce(total_donated, 0) + new.amount,
      pipeline_status = 'donated'
  where id = new.contact_id;
  return new;
end;
$$ language plpgsql security definer;

create trigger donation_updates_contact
  after insert on donations
  for each row execute function update_contact_total_donated();

-- Auto-update contacts.total_pledged when a pledge is created
create or replace function update_contact_total_pledged()
returns trigger as $$
begin
  update contacts
  set total_pledged = coalesce(total_pledged, 0) + new.amount,
      pipeline_status = 'pledged'
  where id = new.contact_id;
  return new;
end;
$$ language plpgsql security definer;

create trigger pledge_updates_contact
  after insert on pledges
  for each row execute function update_contact_total_pledged();

-- Auto-mark follow-ups as overdue
-- (Run this as a Supabase cron job or check on page load)
create or replace function mark_overdue_follow_ups()
returns void as $$
begin
  update follow_ups
  set status = 'overdue'
  where status = 'pending'
    and due_date < now();
end;
$$ language plpgsql security definer;

-- ============================================================
-- 10. ENABLE REALTIME for live updates
-- ============================================================

alter publication supabase_realtime add table contact_notes;
alter publication supabase_realtime add table contact_interactions;
alter publication supabase_realtime add table follow_ups;
alter publication supabase_realtime add table donations;
